# Generated by Django 6.0.7 on 2026-07-19 10:35

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.VeloraUserManager()),
            ],
        ),
    ]
